[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
autoagents = { path = "../../crates/autoagents" }
tokio = { version = "1.43.0", features = ["full"] }
futures = "0.3.31"
